services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    healthcheck:
      test: ["CMD-SHELL", "m_isready - U mysql"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-store-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
      "spring.datasource.username": "${MYSQLDB_USER}",
      "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
      "jwt.expiration": "${JWT_EXPIRATION}",
      "jwt.secret": "${JWT_SECRET}"
      }'
